### PR TITLE
getCurrentPage Method and getTotalPages Method added

### PR DESCRIPTION
**Pull request by haroonabbasi**
To track total number of views and current page view index

### CODE REVIEW

**Comment by jkotchoff** [comment]
Hi Haroon, thanks for the pull request. You removed the exports.setHeight function which is actually in use - we would want that to remain.

Can you also please explain the intent behind exposing the current/total pages?

**Comment by haroonabbasi** [comment]
No it is not removed, strange if you check my code file its there, but git diff show it as removed, strange.
check the fork of my and go controller file and view it you will see!

[check this](https://github.com/haroonabbasi/au.jkotchoff.scrollableView/blob/master/controllers/widget.js)

**Comment by jkotchoff** [comment]
Hmm, maybe your pull request needs to be resubmitted.

**Comment by haroonabbasi** [comment]
leave this pull for now, i will make another fork and will update it again and will send pull request again.

**Pull request closed without merging**
